movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail')
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views


movie_resource = MovieResource()

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie


class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']

movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    title = models.CharField(max_length=255)
    release = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    # output = ', '.join([m.title for m in movies])
    return render(request, 'movies/index.html', {'movies': movies})
    # return HttpResponse("Hello World")
    # return HttpResponse(output)


# try:
def detail(request, movie_id):
    # movies = Movie.objects.get(id=movie_id)
    movies = get_object_or_404(Movie, pk=movie_id)
    # return HttpResponse(movie_id)
    return render(request, 'movies/detail.html', {'movies': movies})
    # except Movie.DoesNotExist:
    #     raise Http404

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends "base.html" %}
{% block content %}

    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Stock</dt>
        <dd>{{ movie.number_in_stock }}</dd>
    </dl>
{% endblock %}

movies/templates/movies/index.html
<!-- <h1>Hello World</h1> -->
{% extends "base.html" %}
{% block content %}

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Number in Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
    </table>

    <tbody>
        {% for movie in movies %}
            <tr>
                <td>
{#                    <a href="/movies/{{ movie.id }}">{{ movie.title }} </a>#}
                    <a href="{% url 'movies:detail' movie.id %}">{{ movie.title }}</a>
                </td>
                <td>{{ movie.genre }}</td>
                <td>{{ movie.number_in_stock }}</td>
                <td>{{ movie.daily_rate }}</td>
            </tr>
        {% endfor %}
    </tbody>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">vidly</a>
        </div>
    </nav>
    <main class="container">
      {% block content %}
      {% endblock  %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script

  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}